// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUserDevices = `-- name: CountUserDevices :one
SELECT COUNT(*) FROM devices WHERE user_id = $1
`

func (q *Queries) CountUserDevices(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, device_id, device_name, device_type, has_camera, has_microphone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at
`

type CreateDeviceParams struct {
	UserID        uuid.UUID
	DeviceID      string
	DeviceName    string
	DeviceType    DeviceType
	HasCamera     sql.NullBool
	HasMicrophone sql.NullBool
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceName,
		arg.DeviceType,
		arg.HasCamera,
		arg.HasMicrophone,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceType,
		&i.HasCamera,
		&i.HasMicrophone,
		&i.IsOnline,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceType,
		&i.HasCamera,
		&i.HasMicrophone,
		&i.IsOnline,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByUserAndDeviceID = `-- name: GetDeviceByUserAndDeviceID :one
SELECT id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at FROM devices WHERE user_id = $1 AND device_id = $2
`

type GetDeviceByUserAndDeviceIDParams struct {
	UserID   uuid.UUID
	DeviceID string
}

func (q *Queries) GetDeviceByUserAndDeviceID(ctx context.Context, arg GetDeviceByUserAndDeviceIDParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByUserAndDeviceID, arg.UserID, arg.DeviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceType,
		&i.HasCamera,
		&i.HasMicrophone,
		&i.IsOnline,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const listOnlineUserDevices = `-- name: ListOnlineUserDevices :many
SELECT id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at FROM devices WHERE user_id = $1 AND is_online = TRUE ORDER BY last_seen DESC
`

func (q *Queries) ListOnlineUserDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceName,
			&i.DeviceType,
			&i.HasCamera,
			&i.HasMicrophone,
			&i.IsOnline,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at FROM devices WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.DeviceName,
			&i.DeviceType,
			&i.HasCamera,
			&i.HasMicrophone,
			&i.IsOnline,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET device_name = COALESCE($2, device_name),
    has_camera = COALESCE($3, has_camera),
    has_microphone = COALESCE($4, has_microphone)
WHERE id = $1
RETURNING id, user_id, device_id, device_name, device_type, has_camera, has_microphone, is_online, last_seen, created_at
`

type UpdateDeviceParams struct {
	ID            uuid.UUID
	DeviceName    string
	HasCamera     sql.NullBool
	HasMicrophone sql.NullBool
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.ID,
		arg.DeviceName,
		arg.HasCamera,
		arg.HasMicrophone,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceType,
		&i.HasCamera,
		&i.HasMicrophone,
		&i.IsOnline,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET last_seen = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateDeviceLastSeen, id)
	return err
}

const updateDeviceOnlineStatus = `-- name: UpdateDeviceOnlineStatus :exec
UPDATE devices
SET is_online = $2, last_seen = NOW()
WHERE id = $1
`

type UpdateDeviceOnlineStatusParams struct {
	ID       uuid.UUID
	IsOnline sql.NullBool
}

func (q *Queries) UpdateDeviceOnlineStatus(ctx context.Context, arg UpdateDeviceOnlineStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceOnlineStatus, arg.ID, arg.IsOnline)
	return err
}
