// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streams.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countActiveUserStreams = `-- name: CountActiveUserStreams :one
SELECT COUNT(*) FROM streams
WHERE user_id = $1 AND status IN ('connecting', 'active', 'paused')
`

func (q *Queries) CountActiveUserStreams(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUserStreams, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStream = `-- name: CreateStream :one
INSERT INTO streams (user_id, source_device_id, target_device_id, stream_type, quality)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, source_device_id, target_device_id, stream_type, status, connection_type, quality, latency_ms, started_at, ended_at
`

type CreateStreamParams struct {
	UserID         uuid.UUID
	SourceDeviceID uuid.NullUUID
	TargetDeviceID uuid.NullUUID
	StreamType     StreamType
	Quality        NullStreamQuality
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error) {
	row := q.db.QueryRowContext(ctx, createStream,
		arg.UserID,
		arg.SourceDeviceID,
		arg.TargetDeviceID,
		arg.StreamType,
		arg.Quality,
	)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.StreamType,
		&i.Status,
		&i.ConnectionType,
		&i.Quality,
		&i.LatencyMs,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endStream = `-- name: EndStream :exec
UPDATE streams
SET status = 'ended', ended_at = NOW()
WHERE id = $1
`

func (q *Queries) EndStream(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, endStream, id)
	return err
}

const getStreamByID = `-- name: GetStreamByID :one
SELECT id, user_id, source_device_id, target_device_id, stream_type, status, connection_type, quality, latency_ms, started_at, ended_at FROM streams WHERE id = $1
`

func (q *Queries) GetStreamByID(ctx context.Context, id uuid.UUID) (Stream, error) {
	row := q.db.QueryRowContext(ctx, getStreamByID, id)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceDeviceID,
		&i.TargetDeviceID,
		&i.StreamType,
		&i.Status,
		&i.ConnectionType,
		&i.Quality,
		&i.LatencyMs,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listActiveUserStreams = `-- name: ListActiveUserStreams :many
SELECT id, user_id, source_device_id, target_device_id, stream_type, status, connection_type, quality, latency_ms, started_at, ended_at FROM streams
WHERE user_id = $1 AND status IN ('connecting', 'active', 'paused')
ORDER BY started_at DESC
`

func (q *Queries) ListActiveUserStreams(ctx context.Context, userID uuid.UUID) ([]Stream, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserStreams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stream
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.StreamType,
			&i.Status,
			&i.ConnectionType,
			&i.Quality,
			&i.LatencyMs,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStreams = `-- name: ListUserStreams :many
SELECT id, user_id, source_device_id, target_device_id, stream_type, status, connection_type, quality, latency_ms, started_at, ended_at FROM streams WHERE user_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListUserStreams(ctx context.Context, userID uuid.UUID) ([]Stream, error) {
	rows, err := q.db.QueryContext(ctx, listUserStreams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stream
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceDeviceID,
			&i.TargetDeviceID,
			&i.StreamType,
			&i.Status,
			&i.ConnectionType,
			&i.Quality,
			&i.LatencyMs,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStreamConnectionType = `-- name: UpdateStreamConnectionType :exec
UPDATE streams
SET connection_type = $2
WHERE id = $1
`

type UpdateStreamConnectionTypeParams struct {
	ID             uuid.UUID
	ConnectionType NullConnectionType
}

func (q *Queries) UpdateStreamConnectionType(ctx context.Context, arg UpdateStreamConnectionTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamConnectionType, arg.ID, arg.ConnectionType)
	return err
}

const updateStreamLatency = `-- name: UpdateStreamLatency :exec
UPDATE streams
SET latency_ms = $2
WHERE id = $1
`

type UpdateStreamLatencyParams struct {
	ID        uuid.UUID
	LatencyMs sql.NullInt32
}

func (q *Queries) UpdateStreamLatency(ctx context.Context, arg UpdateStreamLatencyParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamLatency, arg.ID, arg.LatencyMs)
	return err
}

const updateStreamStatus = `-- name: UpdateStreamStatus :exec
UPDATE streams
SET status = $2
WHERE id = $1
`

type UpdateStreamStatusParams struct {
	ID     uuid.UUID
	Status NullStreamStatus
}

func (q *Queries) UpdateStreamStatus(ctx context.Context, arg UpdateStreamStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamStatus, arg.ID, arg.Status)
	return err
}
