// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id)
VALUES ($1)
RETURNING id, user_id, max_devices, max_concurrent_streams, total_stream_minutes, total_streams_count, default_stream_quality, default_stream_type, created_at, updated_at
`

func (q *Queries) CreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, createUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxDevices,
		&i.MaxConcurrentStreams,
		&i.TotalStreamMinutes,
		&i.TotalStreamsCount,
		&i.DefaultStreamQuality,
		&i.DefaultStreamType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, user_id, max_devices, max_concurrent_streams, total_stream_minutes, total_streams_count, default_stream_quality, default_stream_type, created_at, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxDevices,
		&i.MaxConcurrentStreams,
		&i.TotalStreamMinutes,
		&i.TotalStreamsCount,
		&i.DefaultStreamQuality,
		&i.DefaultStreamType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementStreamCount = `-- name: IncrementStreamCount :exec
UPDATE user_settings
SET total_streams_count = total_streams_count + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementStreamCount(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementStreamCount, userID)
	return err
}

const incrementStreamMinutes = `-- name: IncrementStreamMinutes :exec
UPDATE user_settings
SET total_stream_minutes = total_stream_minutes + $2,
    updated_at = NOW()
WHERE user_id = $1
`

type IncrementStreamMinutesParams struct {
	UserID             uuid.UUID
	TotalStreamMinutes sql.NullInt32
}

func (q *Queries) IncrementStreamMinutes(ctx context.Context, arg IncrementStreamMinutesParams) error {
	_, err := q.db.ExecContext(ctx, incrementStreamMinutes, arg.UserID, arg.TotalStreamMinutes)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET max_devices = COALESCE($2, max_devices),
    max_concurrent_streams = COALESCE($3, max_concurrent_streams),
    default_stream_quality = COALESCE($4, default_stream_quality),
    default_stream_type = COALESCE($5, default_stream_type),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, max_devices, max_concurrent_streams, total_stream_minutes, total_streams_count, default_stream_quality, default_stream_type, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	UserID               uuid.UUID
	MaxDevices           sql.NullInt32
	MaxConcurrentStreams sql.NullInt32
	DefaultStreamQuality NullStreamQuality
	DefaultStreamType    NullStreamType
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, updateUserSettings,
		arg.UserID,
		arg.MaxDevices,
		arg.MaxConcurrentStreams,
		arg.DefaultStreamQuality,
		arg.DefaultStreamType,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxDevices,
		&i.MaxConcurrentStreams,
		&i.TotalStreamMinutes,
		&i.TotalStreamsCount,
		&i.DefaultStreamQuality,
		&i.DefaultStreamType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
